# Generated by Django 5.0.1 on 2025-12-23 03:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField(help_text="The original user query")),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Pharma", "Pharma"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        help_text="Sector assigned by query router",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score from classification (0-1)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("planning", "Planning"),
                            ("researching", "Researching"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quick", "Quick"),
                            ("standard", "Standard"),
                            ("deep", "Deep"),
                        ],
                        help_text="Selected research plan type",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Full report content in markdown"),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        blank=True,
                        help_text="Executive summary extracted from report",
                        null=True,
                    ),
                ),
                (
                    "total_steps",
                    models.IntegerField(
                        default=0, help_text="Total research steps completed"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Total research duration", null=True
                    ),
                ),
                (
                    "citations",
                    models.JSONField(
                        default=list, help_text="List of citations with URLs"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (dimensions covered, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "query",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="core.query",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_number",
                    models.IntegerField(help_text="Sequential step number"),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action being performed (e.g., 'Searching for...')",
                        max_length=200,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Tavily", "Tavily"),
                            ("yfinance", "yfinance"),
                            ("Web", "Web"),
                            ("RAG", "RAG"),
                            ("API", "API"),
                        ],
                        help_text="Data source used",
                        max_length=100,
                    ),
                ),
                (
                    "query_text",
                    models.TextField(help_text="The specific query/search term used"),
                ),
                (
                    "finding",
                    models.TextField(
                        blank=True, help_text="Key finding from this step", null=True
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Raw response data from source", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_steps",
                        to="core.query",
                    ),
                ),
            ],
            options={
                "ordering": ["query", "step_number"],
                "unique_together": {("query", "step_number")},
            },
        ),
    ]
