# Generated by Django 5.0.1 on 2025-12-26 20:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(help_text="Name of the metric", max_length=100),
                ),
                ("metric_value", models.FloatField(help_text="Value of the metric")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("query_count", "Query Count"),
                            ("response_time", "Response Time"),
                            ("success_rate", "Success Rate"),
                            ("sector_distribution", "Sector Distribution"),
                            ("plan_type_distribution", "Plan Type Distribution"),
                            ("tool_usage", "Tool Usage"),
                            ("report_generation", "Report Generation"),
                        ],
                        help_text="Type of metric",
                        max_length=50,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "IT"),
                            ("Pharma", "Pharma"),
                            ("Unknown", "Unknown"),
                            ("All", "All"),
                        ],
                        help_text="Sector for sector-specific metrics",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata for the metric"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "recorded_at"],
                        name="core_analyt_metric__dd7b52_idx",
                    ),
                    models.Index(
                        fields=["sector", "recorded_at"],
                        name="core_analyt_sector_81bdfa_idx",
                    ),
                ],
            },
        ),
    ]
