# Generated by Django 5.0.1 on 2026-01-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_analytics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analytics",
        ),
    ]
